# Dependencies
markdown:         kramdown
highlighter:      rouge

#theme: jekyll-theme-hydeout
title:        C. Blöcher
description:  GameDev and Computer Science

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

#sidebar_home_link:  false

disqus:
  shortname:  https-typecarst-github-io

github:
  repo:       https://github.com/typecarst

social:
  linkedin:   https://www.linkedin.com/in/carsten-bl%C3%B6cher-b7a75185/
  xing:       https://www.xing.com/profile/Carsten_Floeth
