# Dependencies
markdown:         kramdown
highlighter:      rouge

#theme: jekyll-theme-hydeout
title: C. Flöth
description: GameDev and Computer Science

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true
disqus:
  shortname: cfloeth
