# Dependencies
markdown:         kramdown
highlighter:      rouge

theme: jekyll-theme-hydeout
title: Blog von cfloeth
description: This site is used for showcasing projects and different solutions I developed in the past.

sidebar_home_link:  true
